repos:
  - repo: local
    hooks:
    - id: codechecks
      name: codechecks
      stages: ["commit"]
      entry: "tox -e codechecks"
      language: system
      pass_filenames: false
    - id: test
      name: test
      stages: ["push"]
      entry: "make test"
      language: system
      pass_filenames: false
